name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  register:
        uses: ./.github/workflows/setup.yml
        with:
          test-command: './gradlew test --tests "database.Database.createAccount"'
  login:
    needs: register
    uses: ./.github/workflows/setup.yml
    with:
      test-command: './gradlew test --tests "steps.RunCucumberTest"'


